language: node_js
node_js:
  - "7"

before_install:
- sudo apt-get update
- sudo apt-get install build-essential checkinstall
- sudo apt-get install libreadline-gplv2-dev libncursesw5-dev libssl-dev libsqlite3-dev tk-dev libgdbm-dev libc6-dev libbz2-dev
- sudo apt-get install python-software-properties
- sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
- sudo apt-get update
- sudo apt-get install gcc-5.1 g++-5.1
- sudo rm /bin/usr/g++
- sudo ln -s /usr/bin/g++-5 /usr/bin/g++
- npm i node-gyp -g
- npm i nan@2.3.3 -g

script:
    - cd ./demo
    - npm i