language: node_js
node_js:
  - "7"

script:
   - sudo apt-get install build-essential checkinstall
   - sudo apt-get install libreadline-gplv2-dev libncursesw5-dev libssl-dev libsqlite3-dev tk-dev libgdbm-dev libc6-dev libbz2-dev
    - npm i node-gyp -g
    - npm i nan -g
    - cd ./demo
    - npm i